### gotzmann
#use_unsloth: false # true # just for ONE card
upcast_layernorm: false # true # FSDP: Must flatten tensors with uniform dtype but got torch.float16 and torch.float32
enable_liger_kernel: true # works with FSDP

### resume if needed ?
# ignore_data_skip: true
# resume_from_checkpoint: /home/exported/checkpoint-4115

### model
model_name_or_path: NousResearch/Meta-Llama-3.1-8B-Instruct
quantization_bit: 4
double_quantization: false

### method
### all == q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 128 # 64 # 64 # 96
lora_alpha: 16 # 32
lora_dropout: 0.0
use_rslora: true

### dataset
dataset: final
template: llama3
packing: true
neat_packing: true
cutoff_len: 32768 # 16384 # 8192 # 32768 # 16384 # 24576 # 32768 # 16384 # 32768 # 10240 # 32768 # 10240 # 16384 # 8192 # 32768
preprocessing_num_workers: 24

### train
num_train_epochs: 1.0
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 0.00003
lr_scheduler_type: constant_with_warmup # constant # cosine # constant_with_warmup
optim: adamw_8bit # adamw_torch # adamw_torch | adamw_8bit
warmup_steps: 100
# warmup_ratio: 0.1
flash_attn: fa2
bf16: true
#fp16: true

### output
output_dir: /home/exported
logging_steps: 1
save_steps: 300

### eval
# val_size: 0 # 0.1
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 0 # 500

### etc
gradient_checkpointing: true
max_grad_norm: 1.0
ddp_timeout: 180000000
ddp_find_unused_parameters: false # needs to be set as False for LoRA in DDP training
overwrite_cache: true
overwrite_output_dir: true
plot_loss: false
# use_fast_tokenizer: false
# loraplus_lr_ratio: 4.0
# use_reentrant: true
