### gotzmann
# use_unsloth: true # works only for ONE card
ddp_find_unused_parameters: false # needs to be set as False for LoRA in DDP training

### model
# meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: NousResearch/Meta-Llama-3-70B-Instruct
quantization_bit: 4
double_quantization: false
use_fast_tokenizer: false

### method
stage: sft
do_train: true
finetuning_type: lora
# q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
lora_target: q_proj,k_proj,v_proj,o_proj # ,gate_proj,up_proj,down_proj
lora_rank: 32 # 64
lora_alpha: 32 # 64
lora_dropout: 0.0
use_rslora: true
loraplus_lr_ratio: 3.0

### ddp
ddp_timeout: 180000000

### dataset
dataset: final
template: llama3
packing: true
cutoff_len: 2048 # 4096 # 8192 # 1024
# max_samples: 100000 # 1000
overwrite_cache: true
preprocessing_num_workers: 12

### output
output_dir: /home/exported
logging_steps: 1 # 10
save_steps: 50 # 500
plot_loss: false # true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
max_grad_norm: 1.0
learning_rate: 0.00002 # 0.0001
lr_scheduler_type: cosine
num_train_epochs: 3.0
optim: adamw_torch
warmup_steps: 0.03 # 0.1
upcast_layernorm: false # true # false
# flash_attn: fa2
fp16: true

### eval
# val_size: 0 # 0.1
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 0 # 500
