# Train with Continuous PreTraining [ embed_tokens + lm_head ]
# https://www.reddit.com/r/LocalLLaMA/comments/1d86k5y/continued_pretraining_2x_faster_notebook_to/

### gotzmann
#enable_liger_kernel: true # works with FSDP
use_unsloth: true # just for ONE card
upcast_layernorm: true # FSDP: Must flatten tensors with uniform dtype

### resume if needed ?
# ignore_data_skip: true
# resume_from_checkpoint: /home/exported/checkpoint-4115

### model
model_name_or_path: NousResearch/Meta-Llama-3.1-8B-Instruct
quantization_bit: 4
double_quantization: false

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_target: all # all == q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
lora_target: "q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj,embed_tokens,lm_head"
lora_rank: 96
lora_alpha: 32
lora_dropout: 0.0
use_rslora: true

### dataset
dataset: x2
template: llama3
packing: true
neat_packing: true
cutoff_len: 16384 # 8192 | 10240 | 16384 | 24576 | 32768 
preprocessing_num_workers: 48

### train
num_train_epochs: 1.0
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
lr_scheduler_type: cosine # cosine_with_min_lr # constant | constant_with_warmup | linear | cosine
learning_rate: 0.00008
#min_lr: 0.00002
optim: adamw_torch_fused # adamw_torch | adamw_8bit | adamw_torch_fused
weight_decay: 0.00001 # FIXME
warmup_steps: 100
bf16: true # fp16 | bf16

### output
output_dir: /home/exported
logging_steps: 1
save_steps: 300

### etc
flash_attn: fa2
gradient_checkpointing: true
max_grad_norm: 1.0
ddp_timeout: 180000000
ddp_find_unused_parameters: false # False for LoRA in DDP training
overwrite_cache: true
overwrite_output_dir: true
plot_loss: false

# use_fast_tokenizer: false
# loraplus_lr_ratio: 4.0
# use_reentrant: true
# warmup_ratio: 0.1

### eval
# val_size: 0 # 0.1
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 0 # 500
